# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auvsi_suas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionjudgefeedback',
            name='waypoints_captured', ),
        migrations.RemoveField(
            model_name='odlc',
            name='actionable_override', ),
        migrations.AlterField(
            model_name='missionjudgefeedback',
            name='air_drop_accuracy',
            field=models.IntegerField(
                choices=[(0, 'NO_POINTS'), (1, 'WITHIN_05_FT'),
                         (2, 'WITHIN_15_FT'), (3, 'WITHIN_40_FT')]), ),
    ]
