# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auvsi_suas', '0032_on_delete'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='missionclockevent',
            index_together=set([]), ),
        migrations.RemoveField(
            model_name='missionclockevent',
            name='user', ),
        migrations.DeleteModel(
            name='MissionClockEvent', ),
    ]
