# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-11 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auvsi_suas', '0037_odlc_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionjudgefeedback',
            name='air_delivery_accuracy_ft', ),
        migrations.AddField(
            model_name='missionjudgefeedback',
            name='air_drop_accuracy',
            field=models.IntegerField(
                choices=[(0, 'INSUFFICIENT_ACCURACY'), (1, 'WITHIN_05_FT'),
                         (2, 'WITHIN_25_FT'), (3, 'WITHIN_75_FT')],
                default=0),
            preserve_default=False, ),
        migrations.AddField(
            model_name='missionjudgefeedback',
            name='ugv_drove_to_location',
            field=models.BooleanField(default=False),
            preserve_default=False, ),
        migrations.AlterField(
            model_name='odlc',
            name='alphanumeric_color',
            field=models.IntegerField(
                blank=True,
                choices=[(1, 'WHITE'), (2, 'BLACK'), (3, 'GRAY'), (4, 'RED'),
                         (5, 'BLUE'), (6, 'GREEN'), (7, 'YELLOW'),
                         (8, 'PURPLE'), (9, 'BROWN'), (10, 'ORANGE')],
                null=True), ),
        migrations.AlterField(
            model_name='odlc',
            name='background_color',
            field=models.IntegerField(
                blank=True,
                choices=[(1, 'WHITE'), (2, 'BLACK'), (3, 'GRAY'), (4, 'RED'),
                         (5, 'BLUE'), (6, 'GREEN'), (7, 'YELLOW'),
                         (8, 'PURPLE'), (9, 'BROWN'), (10, 'ORANGE')],
                null=True), ),
        migrations.AlterField(
            model_name='odlc',
            name='odlc_type',
            field=models.IntegerField(choices=[(1, 'STANDARD'), (3,
                                                                 'OFF_AXIS'),
                                               (4, 'EMERGENT')]), ),
        migrations.AlterField(
            model_name='odlc',
            name='orientation',
            field=models.IntegerField(
                blank=True,
                choices=[(1, 'N'), (2, 'NE'), (3, 'E'), (4, 'SE'), (5, 'S'),
                         (6, 'SW'), (7, 'W'), (8, 'NW')],
                null=True), ),
        migrations.AlterField(
            model_name='odlc',
            name='shape',
            field=models.IntegerField(
                blank=True,
                choices=[(1, 'CIRCLE'), (2, 'SEMICIRCLE'),
                         (3, 'QUARTER_CIRCLE'), (4, 'TRIANGLE'), (5, 'SQUARE'),
                         (6, 'RECTANGLE'), (7, 'TRAPEZOID'), (8, 'PENTAGON'),
                         (9, 'HEXAGON'), (10, 'HEPTAGON'), (11, 'OCTAGON'),
                         (12, 'STAR'), (13, 'CROSS')],
                null=True), ),
    ]
