# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-29 12:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auvsi_suas', '0038_odlc_choices_air_drop_ugv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odlc',
            old_name='background_color',
            new_name='shape_color', ),
        migrations.AlterField(
            model_name='aerialposition',
            name='altitude_msl',
            field=models.FloatField(validators=[
                django.core.validators.MinValueValidator(-2000),
                django.core.validators.MaxValueValidator(396000)
            ]), ),
        migrations.AlterField(
            model_name='flyzone',
            name='altitude_msl_max',
            field=models.FloatField(validators=[
                django.core.validators.MinValueValidator(-2000),
                django.core.validators.MaxValueValidator(396000)
            ]), ),
        migrations.AlterField(
            model_name='flyzone',
            name='altitude_msl_min',
            field=models.FloatField(validators=[
                django.core.validators.MinValueValidator(-2000),
                django.core.validators.MaxValueValidator(396000)
            ]), ),
        migrations.AlterField(
            model_name='gpsposition',
            name='latitude',
            field=models.FloatField(validators=[
                django.core.validators.MinValueValidator(-90),
                django.core.validators.MaxValueValidator(90)
            ]), ),
        migrations.AlterField(
            model_name='gpsposition',
            name='longitude',
            field=models.FloatField(validators=[
                django.core.validators.MinValueValidator(-180),
                django.core.validators.MaxValueValidator(180)
            ]), ),
        migrations.AlterField(
            model_name='missionconfig',
            name='odlcs',
            field=models.ManyToManyField(
                blank=True,
                related_name='missionconfig_odlc',
                to='auvsi_suas.Odlc'), ),
        migrations.AlterField(
            model_name='missionjudgefeedback',
            name='operational_excellence_percent',
            field=models.FloatField(validators=[
                django.core.validators.MinValueValidator(0),
                django.core.validators.MaxValueValidator(100)
            ]), ),
        migrations.AlterField(
            model_name='missionjudgefeedback',
            name='out_of_bounds',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]), ),
        migrations.AlterField(
            model_name='missionjudgefeedback',
            name='safety_pilot_takeovers',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]), ),
        migrations.AlterField(
            model_name='missionjudgefeedback',
            name='unsafe_out_of_bounds',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]), ),
        migrations.AlterField(
            model_name='missionjudgefeedback',
            name='waypoints_captured',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]), ),
        migrations.AlterField(
            model_name='stationaryobstacle',
            name='cylinder_radius',
            field=models.FloatField(validators=[
                django.core.validators.MinValueValidator(30),
                django.core.validators.MaxValueValidator(300)
            ]), ),
        migrations.AlterField(
            model_name='uastelemetry',
            name='uas_heading',
            field=models.FloatField(validators=[
                django.core.validators.MinValueValidator(0),
                django.core.validators.MaxValueValidator(360)
            ]), ),
    ]
