# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-02 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auvsi_suas', '0039_background_color_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odlc',
            name='odlc_type',
            field=models.IntegerField(choices=[(1, 'STANDARD'), (4, 'EMERGENT')]),
        ),
    ]
