# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-10 13:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auvsi_suas', '0040_remove_off_axis_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aerialposition',
            name='gps_position', ),
        migrations.AddField(
            model_name='aerialposition',
            name='latitude',
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90)
                ]),
            preserve_default=False, ),
        migrations.AddField(
            model_name='aerialposition',
            name='longitude',
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180)
                ]),
            preserve_default=False, ),
    ]
