# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-10 14:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auvsi_suas', '0041_denormalize_aerialposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationaryobstacle',
            name='gps_position', ),
        migrations.RemoveField(
            model_name='uastelemetry',
            name='uas_position', ),
        migrations.RemoveField(
            model_name='waypoint',
            name='position', ),
        migrations.AddField(
            model_name='stationaryobstacle',
            name='latitude',
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90)
                ]),
            preserve_default=False, ),
        migrations.AddField(
            model_name='stationaryobstacle',
            name='longitude',
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180)
                ]),
            preserve_default=False, ),
        migrations.AddField(
            model_name='uastelemetry',
            name='altitude_msl',
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-2000),
                    django.core.validators.MaxValueValidator(396000)
                ]),
            preserve_default=False, ),
        migrations.AddField(
            model_name='uastelemetry',
            name='latitude',
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90)
                ]),
            preserve_default=False, ),
        migrations.AddField(
            model_name='uastelemetry',
            name='longitude',
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180)
                ]),
            preserve_default=False, ),
        migrations.AddField(
            model_name='waypoint',
            name='altitude_msl',
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-2000),
                    django.core.validators.MaxValueValidator(396000)
                ]),
            preserve_default=False, ),
        migrations.AddField(
            model_name='waypoint',
            name='latitude',
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90)
                ]),
            preserve_default=False, ),
        migrations.AddField(
            model_name='waypoint',
            name='longitude',
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180)
                ]),
            preserve_default=False, ),
    ]
