# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  # Forward port for SUAS server
  config.vm.network "forwarded_port", guest: 80,   host: 80
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Sync the repository folder to known path in VM
  config.vm.synced_folder "../", "/home/vagrant/auvsi_suas_competition"

  # Use automated setup script
  config.vm.provision :shell do |shell|
    shell.inline = "cd /home/vagrant/auvsi_suas_competition/setup;
                    ./setup.sh;"
  end

end
