# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  # Forward port for SUAS server
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  # Prepare for Puppet run
  config.vm.provision :shell do |shell|
    shell.inline = "mkdir -p /etc/puppet/modules;
                    puppet module install puppetlabs-apt;"
  end

  # Provision with AUVSI SUAS Puppet manifest
  config.vm.provision "puppet" do |puppet|
    puppet.options = "--modulepath /vagrant/puppet_files/:/etc/puppet/modules/:/usr/share/puppet/modules/"
    puppet.manifests_path = "puppet_files/"
    puppet.manifest_file  = "auvsi_suas.pp"
  end

end
